################################################################################
#
# wpeframework-disneyplus
#
################################################################################

WPEFRAMEWORK_DISNEYPLUS_VERSION = 56301bd58c8ba9b18516eaba602dbd29ced5dd2e
WPEFRAMEWORK_DISNEYPLUS_SITE_METHOD = git
WPEFRAMEWORK_DISNEYPLUS_SITE = git@github.com:WebPlatformForEmbedded/WPEPluginDisneyPlus.git
WPEFRAMEWORK_DISNEYPLUS_INSTALL_STAGING = YES
WPEFRAMEWORK_DISNEYPLUS_DEPENDENCIES = wpeframework disney

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_AUTOSTART),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_AUTOSTART=true
else
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_AUTOSTART=false
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_DEVICE),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_DEVICE="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_DEVICE))"
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_VENDOR),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_VENDOR="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_VENDOR))"
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_REGION),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_REGION="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_REGION))"
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_LANGUAGE),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_LANGUAGE="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_LANGUAGE))"
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_ADVERTISING_ID),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_ADVERTISING_ID="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_ADVERTISING_ID))"
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DISNEYPLUS_GRAPHICS_MODE_720P),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_GRAPHICS_MODE=720p
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DISNEYPLUS_GRAPHICS_MODE_1080P),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_GRAPHICS_MODE=1080p
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DISNEYPLUS_GRAPHICS_MODE_2160P),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_GRAPHICS_MODE=2160p
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_VIDEO_MEMORY),0)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_VIDEO_MEMORY=$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_VIDEO_MEMORY)
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_STACK_SIZE),0)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_STACK_SIZE=$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_STACK_SIZE)
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_PERSONA_ID),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_PERSONA_ID="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_PERSONA_ID))"
endif

ifeq ($(BR2_PACKAGE_DISNEY_TOOLING_SHIELD_ASSISTANT),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_SHIELD_ASSISTANT=ON
else
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_SHIELD_ASSISTANT=OFF
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DISNEYPLUS_MAX_VIDEO_RESOLUTION_SD),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_MAX_VIDEO_RESOLUTION=sd
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DISNEYPLUS_MAX_VIDEO_RESOLUTION_720P60),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_MAX_VIDEO_RESOLUTION=720p60
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DISNEYPLUS_MAX_VIDEO_RESOLUTION_1080P60),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_MAX_VIDEO_RESOLUTION=1080p60
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DISNEYPLUS_MAX_VIDEO_RESOLUTION_2160P60),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_MAX_VIDEO_RESOLUTION=2160p60
endif

WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST = ""
ifeq ($(PLUGIN_DISNEYPLUS_AUDIO_CODECS_AAC),y)
	ifneq ($(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST),"")
	WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST := $(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST),
	endif
	WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST := $(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST)aac
endif
ifeq ($(PLUGIN_DISNEYPLUS_AUDIO_CODECS_AC3),y)
	ifneq ($(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST),"")
	WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST := $(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST),
	endif
	WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST := $(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST)ac3
endif
ifeq ($(PLUGIN_DISNEYPLUS_AUDIO_CODECS_EAC3),y)
	ifneq ($(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST),"")
	WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST := $(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST),
	endif
	WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST := $(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST)eac3
endif
ifeq ($(PLUGIN_DISNEYPLUS_AUDIO_CODECS_ATMOS),y)
	ifneq ($(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST),"")
	WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST := $(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST),
	endif
	WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST := $(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST)atmos
endif
ifneq ($(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_AUDIO_CODECS="$(call qstrip,$(WPEFRAMEWORK_DISNEYPLUS_AUDIO_CODECS_LIST))"
endif

WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST = ""
ifeq ($(PLUGIN_DISNEYPLUS_VIDEO_PROFILE_H264_MAIN),y)
	ifneq ($(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST),"")
	WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST := $(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST),
	endif
	WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST := $(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST)h264_main
endif
ifeq ($(PLUGIN_DISNEYPLUS_VIDEO_PROFILE_H264_HIGH),y)
	ifneq ($(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST),"")
	WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST := $(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST),
	endif
	WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST := $(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST)h264_high
endif
ifeq ($(PLUGIN_DISNEYPLUS_VIDEO_PROFILE_HEVC_MAIN),y)
	ifneq ($(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST),"")
	WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST := $(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST),
	endif
	WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST := $(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST)hevc_main
endif
ifeq ($(PLUGIN_DISNEYPLUS_VIDEO_PROFILE_HEVC_MAIN_10),y)
	ifneq ($(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST),"")
	WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST := $(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST),
	endif
	WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST := $(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST)hevc_main_10
endif
ifneq ($(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_VIDEO_PROFILES="$(call qstrip,$(WPEFRAMEWORK_DISNEYPLUS_VIDEO_PROFILES_LIST))"
endif


$(eval $(cmake-package))
