
name: RPI-Makefile-CI

on:
  push:
    branches: Divya-test
 

jobs:
  build:

    runs-on: self-hosted

    steps:
   
    - run:
        git config --global user.email "divdus@gmail.com" && git config --global user.name "Divya-563"
   

    - name: Compile
      run: make
    
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
          format: 'YYYY-MM-DD-HH-mm-ss'
        
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: images_${{ steps.time.outputs.time }}
        path: output/images/
        
    
        
       
   
