
name: RPI-Makefile-CI

on:
  push:
    branches: R4
  pull_request:
    branches: R4

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - run:
        git config --global user.email "divdus@gmail.com" && git config --global user.name "Divya-563"
        
    - name: configure
      run: make raspberrypi3_wpe_ml_defconfig
      
    - name: Install generators
      run: |
        cmake -G Ninja -S ThunderTools -B Release/build/ThunderTools \
        -DCMAKE_INSTALL_PREFIX=${{matrix.build_type}}/install/usr
        cmake --build Release/build/ThunderTools --target install

    - name: Compile
      run: make
    
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: rpi_rootfs.tar
        path: output/images/rootfs.tar
        if-no-files-found: "No Rootfs tar created!!!"
       
   

