
name: RPI-Makefile-CI

on:
  push:
    branches: R4
  pull_request:
    branches: R4

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run:
        git config --global user.email "divdus@gmail.com" && git config --global user.name "Divya-563"
        
    - name : Add SSH key
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: mkdir -p /home/runner/.ssh
           ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
           echo "${{ secrets.D_SSH_KEY }}" > /home/runner/.ssh/github_actions
           chmod 600 /home/runner/.ssh/github_actions
           ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
           ssh-add /home/runner/.ssh/github_actions 
        
    - name: clean-up
      run: make clean
      
    - name: configure
      run: make raspberrypi3_wpe_ml_defconfig

    - name: Compile
      run: make
    
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: rpi_rootfs.tar
        path: output/images/rootfs.tar
        if-no-files-found: "No Rootfs tar created!!!"
       
   

