name: Test

on:
  push:
    branches: R4
 

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - run:
        git config --global user.email "divdus@gmail.com" && git config --global user.name "Divya-563"
        
    - name : Add SSH key
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: mkdir -p /home/runner/.ssh
           ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
           echo "${{ secrets.DOCKERHUB_TOKEN }}" > /home/runner/.ssh/github_actions
           chmod 600 /home/runner/.ssh/github_actions
           ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
           ssh-add /home/runner/.ssh/github_actions 
               ssh-add /home/runner/.ssh/github_actions 
        
    - name: configure
      run: make raspberrypi3_wpe_ml_defconfig
   
    - name: Compile
      run: make libprovision-rebuild
