name: Test

on:
  push:
    branches: R4
 

jobs:
  build:

    runs-on: self-hosted
  
    steps:
          - name: configure
            run: make raspberrypi3_wpe_ml_defconfig
   
          - name: Compile
            run: make libprovision-rebuild
