name: Test

on:
  push:
    branches: R4
 

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - run:
        git config --global user.email "divdus@gmail.com" && git config --global user.name "Divya-563"    
   
        
    - name: configure
      run: make raspberrypi3_wpe_ml_defconfig
   
    - name: Compile
      run: make libprovision-rebuild
